### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Abu-Muatafa** [crond-jaist/GridAttackSim#1]
I am running the simulation and I am facing the following errors:
mv: cannot stat 'baseprice_clearedprice_clearedquantity.csv': No such file or directory
mv: cannot stat 'totalload.csv': No such file or directory

**Comment by crond-jaist** [comment]
Hello,
Unfortunately your description doesn't help me understand the issue you are facing. I suggest you check again that you have followed all the steps in the documentation for setting up the GridAttackSim system, then try again. 
If the simulation still doesn't run, please describe in details your setup and actions, so that we can try to diagnose the problem.
Best wishes,
Razvan

**Comment by Abu-Muatafa** [comment]
Thank you very much for your prompt reply.

Actually, I run the simulations with 13 nodes, 73 houses, Demand and Response application, Nefarious activity Attack, and 1- Channel Jamming-Cluster.  The results appears as following:

You selected Attack ID: 1
- Category Name:  Nefarious Activity
- Attack Type: Channel Jamming - Cluster
- Description:  Since smart grid uses IP protocol and TCP/IP stack, it becomes subject to DoS attacks and to the vulnerabilities inherent in the TCP/IP stack. DoS attacks might attempt to delay, block, or corrupt information transmission in order to make smart grid resources unavailable
- Attack Component:  Network
- Start Time:  12:00:00
- End Time: 18:00:00
- Affected Value: 
	- delay_cluster = 100
	- data_rate_cluster = 1000000
The Simulation is running!
Process PID: 38419
Finished!
mv: cannot stat 'baseprice_clearedprice_clearedquantity.csv': No such file or directory
mv: cannot stat 'totalload.csv': No such file or directory

**Comment by leduytanjaist2016** [comment]
Hi,
Thank you for your question,
Please simply add 2 blank CSV files name "baseprice_clearedprice_clearedquantity.csv" and 'totalload.csv' under the folder Database/Grid_Database_Name. For example, Database/13_Nodes_15_Houses.
Then the program can be executed normally.
Good luck!
